### ISSUE TITLE
Update for 3.4

### ISSUE THREAD

**Issue by jardakotesovec** [pkp/defaultManuscript#41]

**Comment by saalam** [comment]
Hi,
Since a lot of journals are using this amazing theme, Is there any estimation time to update this theme to be compatible with OJS 3.4.X? we are using this theme in our journals and we can't upgrade until the update released.
Kind regards,
-Salam

**Comment by jardakotesovec** [comment]
Hi @saalam,
thank you for bringing this to my attention. I will make sure new version is release before the end of next week.

@asmecher or @Vitaliy-1 Can you have a quick look? Per my testing these changes should be sufficient - https://github.com/pkp/defaultManuscript/pull/43

Sticked with using older index.php mechanism on @asmecher recommendation as new mechanism assume that the plugin folder name and the plugin class has the same name and renaming would cause troubles for users who are upgrading and have class name already in **versions** table.

**Comment by asmecher** [comment]
Thanks, @jardakotesovec! Just a few miscellaneous cleanups to recommend.

**Comment by asmecher** [comment]
Merged -- thanks, @jardakotesovec, that looks great! Is this issue ready to be closed?

**Comment by jardakotesovec** [comment]
@asmecher I will test installation from gallery tomorrow before closing to make sure its all good.

**Comment by jardakotesovec** [comment]
Hi @saalam,
version 1.0.4 which is compatible with OJS 3.4 is now available in plugin gallery. Closing.

**Comment by saalam** [comment]
Hi @jardakotesovec, 
Thank you all for your effort to update it. I download it from the plugin galley and the theme looks amazing. 
Again really appreciate your time and work
Regards,
-Salam
