### ISSUE TITLE
available for OJS 3.3.0-15

### ISSUE THREAD

**Issue by Ppantaleo** [pkp/defaultManuscript#42]
Hello, is it available for OJS 3.3.0-15? I load it but it shows the same as Default.

**Comment by jardakotesovec** [comment]
@Ppantaleo Hi, yes 3.3.0-15 should work just fine. Can you try to delete the browser cache?

**Comment by jardakotesovec** [comment]
@Ppantaleo I think this is most likely browser cache. If you are still having troubles please re-open or open new issue. Closing for now.
